# Generated by Django 3.2.4 on 2021-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('published',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(blank=True, max_length=200, verbose_name='post preview'),
        ),
    ]
