# A template of docker-compose configuration file.
# Copy as `docker-compose.yaml` and setup for local usage.
#
# BASH: `$ cp docker-compose.template.yaml docker-compose.yaml`
#
# Any changes of this configuration file must be taken into account on the production server

version: "3.8"

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  postgres:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./postgres.env

  platform:
    build: .
    restart: always
    depends_on:
      - postgres
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
      - .:/code
    env_file:
      - ./platform.env
      - ./postgres.env

  nginx:
    image: nginx:1.23.2
    depends_on:
      - platform
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
      - ./host.local.conf:/etc/nginx/conf.d/default.conf
