version: "3.8"

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

services:
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: blog/.env

  platform:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
    env_file: blog/.env

  nginx:
    image: nginx:1.23.2
    depends_on:
      - platform
    ports:
      - 80:80
      - 443:443
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
      - ./host.conf:/etc/nginx/conf.d/default.conf
