# Generated by Django 3.2.4 on 2021-07-13 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_rename_comment_notecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
